### ISSUE TITLE
单元测试在使用模板时跑不起来

### ISSUE THREAD

**Issue by rainfore** [vusion/vusion-cli#37]
```
ERROR LOG: '[Vue warn]: Property or method "inspect" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

**Comment by haoxutong** [comment]
`it('(default)', (done) => {
        setTimeout(() => {
            vm = createVMFromTemplate(`<u-tabs ref="tabs">
                <u-tab title="TabA">ContentA</u-tab>
                <u-tab title="TabB">ContentB</u-tab>
                <u-tab title="TabC">ContentC</u-tab>
            </u-tabs>`);

            tabs = vm.$refs.tabs;
            vm.$nextTick(() => {
                expect(tabs.selectedVM).to.equal(tabs.itemVMs[0]);
                done();
            });
        }, 0);
    });
`
解决方案：需要使用setTimeout和nextTick，具体见代码
原因：执行顺序，具体待详细研究
